version: "3"
services:
  
  frontend:
   build:
      context: ./frontend
      dockerfile: Dockerfile
   ports:
    -  8000:3000
   container_name: mern-client
   networks:
    -  mern-stack-net
   depends_on:
    - backend
   stdin_open: true
   tty: true

  backend:
   build:
      context: ./backend
      dockerfile: Dockerfile
   ports:
     - 8001:3001
   container_name: mern-server
   networks:
     - mern-stack-net

networks:
  mern-stack-net:
    driver: bridge

